-- Online Shop System: basic, single-inventory B2C schema.
-- All monetary values are VND; the application uses Asia/Ho_Chi_Minh for reports.

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(255) NOT NULL,
    password_hash varchar(255) NOT NULL,
    full_name varchar(150) NOT NULL,
    phone varchar(30),
    role varchar(30) NOT NULL CHECK (role IN ('CUSTOMER','ADMIN','MANAGER','SUPPORT','WAREHOUSE','DELIVERY')),
    status varchar(30) NOT NULL DEFAULT 'PENDING_VERIFICATION' CHECK (status IN ('PENDING_VERIFICATION','ACTIVE','INACTIVE','LOCKED')),
    verified_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT users_email_normalized CHECK (email = lower(btrim(email)))
);
CREATE UNIQUE INDEX users_email_uq ON users (email);

CREATE TABLE user_addresses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id),
    recipient_name varchar(150) NOT NULL,
    phone varchar(30) NOT NULL,
    address_line varchar(300) NOT NULL,
    ward varchar(120),
    district varchar(120),
    province varchar(120) NOT NULL,
    is_default boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX one_default_address_per_user ON user_addresses(user_id) WHERE is_default;

CREATE TABLE auth_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id),
    token_hash varchar(255) NOT NULL UNIQUE,
    purpose varchar(30) NOT NULL CHECK (purpose IN ('EMAIL_VERIFICATION','PASSWORD_RESET')),
    expires_at timestamptz NOT NULL,
    used_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT auth_token_dates CHECK (expires_at > created_at)
);

CREATE TABLE categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(150) NOT NULL UNIQUE,
    description text,
    status varchar(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id bigint NOT NULL REFERENCES categories(id),
    sku varchar(80) NOT NULL UNIQUE,
    name varchar(200) NOT NULL,
    description text,
    image_url varchar(500),
    price numeric(15,2) NOT NULL CHECK (price >= 0),
    stock_on_hand integer NOT NULL DEFAULT 0 CHECK (stock_on_hand >= 0),
    stock_reserved integer NOT NULL DEFAULT 0 CHECK (stock_reserved >= 0),
    reorder_threshold integer NOT NULL DEFAULT 0 CHECK (reorder_threshold >= 0),
    status varchar(20) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','ACTIVE','INACTIVE','ARCHIVED')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT product_reservation_limit CHECK (stock_reserved <= stock_on_hand)
);
CREATE INDEX products_category_status_idx ON products(category_id,status);

CREATE TABLE carts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint REFERENCES users(id),
    guest_session_hash varchar(255),
    status varchar(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','CONVERTED','EXPIRED')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT cart_one_owner CHECK ((user_id IS NOT NULL) <> (guest_session_hash IS NOT NULL))
);
CREATE UNIQUE INDEX one_active_customer_cart ON carts(user_id) WHERE status = 'ACTIVE' AND user_id IS NOT NULL;
CREATE UNIQUE INDEX one_active_guest_cart ON carts(guest_session_hash) WHERE status = 'ACTIVE' AND guest_session_hash IS NOT NULL;

CREATE TABLE cart_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id bigint NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
    product_id bigint NOT NULL REFERENCES products(id),
    quantity integer NOT NULL CHECK (quantity > 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (cart_id,product_id)
);

CREATE TABLE vouchers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(60) NOT NULL UNIQUE,
    discount_type varchar(20) NOT NULL CHECK (discount_type IN ('FIXED','PERCENT')),
    discount_value numeric(15,2) NOT NULL CHECK (discount_value > 0),
    max_discount numeric(15,2) CHECK (max_discount > 0),
    min_order_amount numeric(15,2) NOT NULL DEFAULT 0 CHECK (min_order_amount >= 0),
    usage_limit integer NOT NULL CHECK (usage_limit > 0),
    valid_from timestamptz NOT NULL,
    valid_until timestamptz NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','ACTIVE','INACTIVE','EXPIRED')),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT voucher_dates CHECK (valid_until > valid_from),
    CONSTRAINT voucher_percentage CHECK (discount_type <> 'PERCENT' OR discount_value <= 100)
);

CREATE TABLE orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_code varchar(40) NOT NULL UNIQUE,
    customer_id bigint NOT NULL REFERENCES users(id),
    cart_id bigint REFERENCES carts(id),
    voucher_id bigint REFERENCES vouchers(id),
    status varchar(35) NOT NULL CHECK (status IN ('AWAITING_PAYMENT','PENDING_CONFIRMATION','CONFIRMED','READY_FOR_DELIVERY','ASSIGNED','DELIVERING','DELIVERED','DELIVERY_FAILED','RETURNED_TO_WAREHOUSE','CANCELLED')),
    payment_method varchar(20) NOT NULL CHECK (payment_method IN ('SIMULATED_QR','COD')),
    recipient_name varchar(150) NOT NULL,
    recipient_phone varchar(30) NOT NULL,
    shipping_address varchar(600) NOT NULL,
    subtotal numeric(15,2) NOT NULL CHECK (subtotal >= 0),
    discount_amount numeric(15,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    shipping_fee numeric(15,2) NOT NULL DEFAULT 0 CHECK (shipping_fee >= 0),
    total_amount numeric(15,2) NOT NULL CHECK (total_amount >= 0),
    internal_note text,
    confirmed_by bigint REFERENCES users(id),
    confirmed_at timestamptz,
    delivered_at timestamptz,
    cancelled_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT order_total_matches CHECK (total_amount = subtotal - discount_amount + shipping_fee AND discount_amount <= subtotal),
    CONSTRAINT order_initial_method CHECK ((payment_method = 'SIMULATED_QR' AND status <> 'PENDING_CONFIRMATION') OR payment_method = 'COD')
);
CREATE INDEX orders_customer_created_idx ON orders(customer_id,created_at DESC);
CREATE INDEX orders_status_created_idx ON orders(status,created_at);

CREATE TABLE order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES orders(id),
    product_id bigint NOT NULL REFERENCES products(id),
    sku_snapshot varchar(80) NOT NULL,
    name_snapshot varchar(200) NOT NULL,
    unit_price numeric(15,2) NOT NULL CHECK (unit_price >= 0),
    quantity integer NOT NULL CHECK (quantity > 0),
    discount_amount numeric(15,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    line_total numeric(15,2) NOT NULL CHECK (line_total >= 0),
    CONSTRAINT order_item_total_matches CHECK (line_total = unit_price * quantity - discount_amount),
    UNIQUE (order_id,product_id),
    UNIQUE (id,order_id)
);

CREATE TABLE voucher_usages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id bigint NOT NULL REFERENCES vouchers(id),
    order_id bigint NOT NULL UNIQUE REFERENCES orders(id),
    status varchar(20) NOT NULL CHECK (status IN ('RESERVED','CONSUMED','RELEASED')),
    reserved_at timestamptz NOT NULL DEFAULT now(),
    consumed_at timestamptz,
    released_at timestamptz
);
CREATE INDEX voucher_usages_count_idx ON voucher_usages(voucher_id,status);

CREATE TABLE payment_attempts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES orders(id),
    attempt_number smallint NOT NULL CHECK (attempt_number BETWEEN 1 AND 3),
    method varchar(20) NOT NULL CHECK (method IN ('SIMULATED_QR','COD')),
    status varchar(25) NOT NULL CHECK (status IN ('PENDING','UNPAID','PAID','FAILED','EXPIRED','CANCELLED')),
    amount numeric(15,2) NOT NULL CHECK (amount >= 0),
    simulation_code varchar(80) UNIQUE,
    expires_at timestamptz,
    paid_at timestamptz,
    recorded_by bigint REFERENCES users(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (order_id,attempt_number),
    CONSTRAINT payment_attempt_method CHECK ((method = 'SIMULATED_QR' AND simulation_code IS NOT NULL AND expires_at IS NOT NULL) OR (method = 'COD' AND simulation_code IS NULL AND expires_at IS NULL AND attempt_number = 1))
);
CREATE UNIQUE INDEX one_pending_payment_per_order ON payment_attempts(order_id) WHERE status = 'PENDING';

CREATE TABLE stock_reservations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_item_id bigint NOT NULL REFERENCES order_items(id),
    payment_attempt_id bigint REFERENCES payment_attempts(id),
    quantity integer NOT NULL CHECK (quantity > 0),
    status varchar(20) NOT NULL CHECK (status IN ('ACTIVE','CONSUMED','RELEASED')),
    expires_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    CONSTRAINT qr_reservation_expires CHECK (payment_attempt_id IS NULL OR expires_at IS NOT NULL)
);
CREATE UNIQUE INDEX one_active_reservation_per_item ON stock_reservations(order_item_id) WHERE status = 'ACTIVE';
CREATE INDEX stock_reservations_expiry_idx ON stock_reservations(expires_at) WHERE status = 'ACTIVE';

CREATE TABLE inventory_movements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint NOT NULL REFERENCES products(id),
    movement_type varchar(30) NOT NULL CHECK (movement_type IN ('MANUAL_ADJUSTMENT','ORDER_PACKED','RETURN_RESTOCK')),
    quantity_delta integer NOT NULL CHECK (quantity_delta <> 0),
    stock_after integer NOT NULL CHECK (stock_after >= 0),
    order_item_id bigint REFERENCES order_items(id),
    reason varchar(500) NOT NULL,
    performed_by bigint REFERENCES users(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT manual_movement_actor CHECK (movement_type <> 'MANUAL_ADJUSTMENT' OR performed_by IS NOT NULL)
);
CREATE INDEX inventory_movements_product_idx ON inventory_movements(product_id,created_at DESC);

CREATE TABLE shipments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL UNIQUE REFERENCES orders(id),
    assigned_staff_id bigint REFERENCES users(id),
    status varchar(30) NOT NULL CHECK (status IN ('READY','ASSIGNED','IN_TRANSIT','DELIVERED','DELIVERY_FAILED','RETURNED_TO_WAREHOUSE')),
    assigned_at timestamptz,
    cod_amount numeric(15,2) NOT NULL DEFAULT 0 CHECK (cod_amount >= 0),
    cod_collected_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE delivery_attempts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id bigint NOT NULL REFERENCES shipments(id),
    attempt_number smallint NOT NULL CHECK (attempt_number BETWEEN 1 AND 2),
    delivery_staff_id bigint NOT NULL REFERENCES users(id),
    status varchar(25) NOT NULL CHECK (status IN ('ASSIGNED','IN_TRANSIT','DELIVERED','FAILED','RETURNED')),
    failure_reason varchar(500),
    started_at timestamptz,
    finished_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (shipment_id,attempt_number),
    CONSTRAINT delivery_failure_reason CHECK (status NOT IN ('FAILED','RETURNED') OR failure_reason IS NOT NULL)
);

CREATE TABLE return_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES orders(id),
    customer_id bigint NOT NULL REFERENCES users(id),
    request_type varchar(25) NOT NULL CHECK (request_type IN ('REFUND_ONLY','RETURN_AND_REFUND')),
    status varchar(30) NOT NULL CHECK (status IN ('REQUESTED','UNDER_REVIEW','MORE_INFO_REQUIRED','RETURN_AUTHORIZED','INSPECTED','APPROVED','REJECTED','REFUND_PENDING','REFUNDED','PARTIALLY_REFUNDED','CLOSED')),
    reason text NOT NULL,
    evidence_url varchar(500),
    decision_note text,
    decided_by bigint REFERENCES users(id),
    decided_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (id,order_id)
);
CREATE INDEX return_requests_order_idx ON return_requests(order_id,created_at DESC);

CREATE TABLE return_request_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_request_id bigint NOT NULL,
    order_id bigint NOT NULL,
    order_item_id bigint NOT NULL,
    quantity integer NOT NULL CHECK (quantity > 0),
    refund_amount numeric(15,2) NOT NULL CHECK (refund_amount >= 0),
    FOREIGN KEY (return_request_id,order_id) REFERENCES return_requests(id,order_id),
    FOREIGN KEY (order_item_id,order_id) REFERENCES order_items(id,order_id),
    UNIQUE (return_request_id,order_item_id)
);

CREATE TABLE return_inspections (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_request_item_id bigint NOT NULL UNIQUE REFERENCES return_request_items(id),
    inspected_by bigint NOT NULL REFERENCES users(id),
    received_quantity integer NOT NULL CHECK (received_quantity >= 0),
    condition_note text NOT NULL,
    restock_quantity integer NOT NULL DEFAULT 0 CHECK (restock_quantity >= 0),
    result varchar(20) NOT NULL CHECK (result IN ('ELIGIBLE','NOT_ELIGIBLE')),
    inspected_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT inspection_restock_limit CHECK (restock_quantity <= received_quantity)
);

CREATE TABLE refunds (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_request_id bigint UNIQUE REFERENCES return_requests(id),
    order_id bigint NOT NULL REFERENCES orders(id),
    reason varchar(30) NOT NULL CHECK (reason IN ('CUSTOMER_RETURN','CANCELLED_PAID_ORDER','FAILED_PREPAID_DELIVERY')),
    method varchar(25) NOT NULL CHECK (method IN ('SIMULATED_QR','MANUAL_COD')),
    status varchar(20) NOT NULL CHECK (status IN ('PENDING','COMPLETED','FAILED')),
    amount numeric(15,2) NOT NULL CHECK (amount > 0),
    idempotency_key varchar(100) NOT NULL UNIQUE,
    approved_by bigint NOT NULL REFERENCES users(id),
    completed_by bigint REFERENCES users(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,
    CONSTRAINT refund_completion CHECK (status <> 'COMPLETED' OR completed_at IS NOT NULL)
);

CREATE TABLE support_tickets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id bigint NOT NULL REFERENCES users(id),
    order_id bigint REFERENCES orders(id),
    subject varchar(200) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','IN_PROGRESS','RESOLVED','CLOSED')),
    assigned_staff_id bigint REFERENCES users(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE ticket_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id bigint NOT NULL REFERENCES support_tickets(id),
    sender_id bigint NOT NULL REFERENCES users(id),
    message text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ticket_messages_ticket_idx ON ticket_messages(ticket_id,created_at);

CREATE TABLE product_reviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_item_id bigint NOT NULL UNIQUE REFERENCES order_items(id),
    customer_id bigint NOT NULL REFERENCES users(id),
    rating smallint NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment text,
    status varchar(20) NOT NULL DEFAULT 'VISIBLE' CHECK (status IN ('VISIBLE','HIDDEN')),
    moderated_by bigint REFERENCES users(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE staff_daily_reports (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id bigint NOT NULL REFERENCES users(id),
    report_date date NOT NULL,
    content text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (staff_id,report_date)
);

CREATE TABLE system_settings (
    setting_key varchar(80) PRIMARY KEY,
    value_text varchar(300) NOT NULL,
    description varchar(300) NOT NULL,
    updated_by bigint REFERENCES users(id),
    updated_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO system_settings(setting_key,value_text,description) VALUES
    ('qr_expiry_minutes','15','Lifetime of a simulated QR payment attempt'),
    ('max_qr_attempts','3','Maximum simulated QR attempts per order'),
    ('return_window_days','7','Return eligibility after delivery'),
    ('max_saved_addresses','10','Maximum saved addresses per customer'),
    ('max_delivery_attempts','2','Maximum delivery attempts per order'),
    ('reporting_time_zone','Asia/Ho_Chi_Minh','Time zone for business reports');

CREATE TABLE audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id bigint REFERENCES users(id),
    action varchar(100) NOT NULL,
    entity_type varchar(80) NOT NULL,
    entity_id varchar(80),
    details jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX audit_logs_entity_idx ON audit_logs(entity_type,entity_id,created_at DESC);
CREATE INDEX audit_logs_actor_idx ON audit_logs(actor_id,created_at DESC);

-- Operational history is append-only. Corrections require a new event.
CREATE FUNCTION reject_history_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'History records are append-only: %', TG_TABLE_NAME;
END;
$$;
CREATE TRIGGER inventory_movements_append_only
    BEFORE UPDATE OR DELETE ON inventory_movements
    FOR EACH ROW EXECUTE FUNCTION reject_history_mutation();
CREATE TRIGGER audit_logs_append_only
    BEFORE UPDATE OR DELETE ON audit_logs
    FOR EACH ROW EXECUTE FUNCTION reject_history_mutation();
