-- Simple local-first bearer sessions. Never store the raw token.
CREATE TABLE user_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id),
    token_hash char(64) NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT user_session_expiry CHECK (expires_at > created_at)
);
CREATE INDEX user_sessions_user_idx ON user_sessions(user_id,expires_at DESC);
