-- Authentication hardening. Raw login, invitation and MFA secrets are never stored.
CREATE TABLE auth_rate_limits (
    limit_key char(64) PRIMARY KEY,
    attempt_count integer NOT NULL,
    window_started_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE user_sessions ADD COLUMN ip_address varchar(64);
ALTER TABLE user_sessions ADD COLUMN user_agent varchar(300);
ALTER TABLE user_sessions ADD COLUMN last_seen_at timestamptz;

CREATE TABLE staff_invitations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(255) NOT NULL,
    full_name varchar(150) NOT NULL,
    phone varchar(30),
    role varchar(30) NOT NULL CHECK (role IN ('ADMIN','MANAGER','SUPPORT','WAREHOUSE','DELIVERY')),
    token_hash char(64) NOT NULL UNIQUE,
    invited_by bigint NOT NULL REFERENCES users(id),
    expires_at timestamptz NOT NULL,
    accepted_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX staff_invitations_email_idx ON staff_invitations(email,created_at DESC);

ALTER TABLE users ADD COLUMN mfa_enabled boolean NOT NULL DEFAULT false;
CREATE TABLE email_mfa_challenges (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id),
    challenge_hash char(64) NOT NULL UNIQUE,
    code_hash char(64) NOT NULL,
    purpose varchar(20) NOT NULL CHECK (purpose IN ('LOGIN','ENROLL')),
    attempts integer NOT NULL DEFAULT 0,
    expires_at timestamptz NOT NULL,
    used_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX email_mfa_user_idx ON email_mfa_challenges(user_id,created_at DESC);
