-- High-entropy, single-use recovery codes are stored only as hashes.
CREATE TABLE mfa_recovery_codes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id),
    code_hash char(64) NOT NULL UNIQUE,
    used_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX mfa_recovery_codes_available_idx ON mfa_recovery_codes(user_id)
    WHERE used_at IS NULL;
